# Generated by Django 4.0.6 on 2022-07-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='codigo_curso',
            new_name='codigoCurso',
        ),
    ]
